### PR TITLE
Add credits screen

### PR DESCRIPTION
**Pull request by Bafou**

### CODE REVIEW

**Comment by LucasDelvallet** [comment]
It's good, but the "Informations" Title should be in the status bar, plus we may want a small margin so the text isn't right at the beginning of the screen

screenshot 23 nov 2016 7_33_48 am

**Comment by Bafou** [comment]
screenshot_2016-11-28-21-27-37
An other screenshoot with the changes added.

**Comment by FlorianDoublet** [comment]
Here is the new credit screen

screenshot_20161130-105522

**Comment by LucasDelvallet** [comment]
Approved.

[Approved with PullApprove](https://pullapprove.com/Bafou/PVviter/pull-request/27/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Bafou/PVviter)

**Comment by joffre** [comment]
Approved !

[Approved with PullApprove](https://pullapprove.com/Bafou/PVviter/pull-request/27/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Bafou/PVviter)

**Pull request merged**
